### ISSUE TITLE
Editor Window no longer updates

### ISSUE THREAD

**Issue by painweaver** [stayradiated/terminal.sexy#23]
The Editor Window does not update with the newly chosen color from Color Picker window. I tried in Fire Fox and Chrome on Arch, Gnome and Windows 7 and none worked. Terminal.sexy was just working for me a couple weeks ago, could this be from the newest update?

**Comment by stayradiated** [comment]
Thank you for pointing this out.
I'm not sure what the cause of the issue is right now, so I have reverted the live site to v0.2.6a.

I really need to get some proper tests written so stuff like this doesn't happen again.

**Comment by stayradiated** [comment]
Fixed.
