### ISSUE TITLE
Messed up xfce4-terminal exporting

### ISSUE THREAD

**Issue by dglava** [stayradiated/terminal.sexy#30]
Using the export feature to get an xfce-terminal config gives us something like this:
```
[Configuration]
ColorCursor=#c7c7ccccd1d1
ColorForeground=#c7c7ccccd1d1
ColorBackground=#1c1c20202323
...
```
Each hex value in the triplet gets doubled. Instead of **#c7ccd1** we get **#c7c7ccccd1d1**.

**Comment by Powersource** [comment]
Huh, seems to happen to Guake too and I can't see any obvious issue in termcolors https://github.com/stayradiated/termcolors/tree/master/templates

**Comment by Powersource** [comment]
Oh wait, wrong files. It does seem to call toDoubleHex instead of just toHex for some reason. Sure it doesn't work if you put it in the conf file? https://github.com/stayradiated/termcolors/tree/master/lib/formats

**Comment by dglava** [comment]
It seems to work. However, choosing one of the provided color themes from the GUI writes it in the usual #XYXYXY format.
Should I close this here and reopen on the termcolors issue tracker?

**Comment by Powersource** [comment]
Sounds like intended behaviour http://stackoverflow.com/a/11169323/3605357

**Comment by dglava** [comment]
That sounds reasonable. I guess this is solved.
