### ISSUE TITLE
Scheme Import doesn't work

### ISSUE THREAD

**Issue by gandalf3** [stayradiated/terminal.sexy#36]
When I try to import a colorscheme, I get an error:
`Uncaught TypeError: Cannot read property 'background' of undefined`
I can reproduce this in both Firefox 54 and Chromium 58.

It doesn't appear to matter what format is selected or the content of the colorsheme.

**Comment by stayradiated** [comment]
Thank you for raising this issue. I have a found a fix and have released it in the `v0.4.0` update.
